CREATE DATABASE AAF
ON PRIMARY
(NAME = AFF_DATA,  
FILENAME = 'D:\projects\C#\AAF\AFF_DATA.MDF',
SIZE = 5MB,  
MAXSIZE = 10MB,  
FILEGROWTH  = 2%
)  
LOG ON  
(NAME = AFF_LOGICO,  
FILENAME = 'D:\projects\C#\AAF\AFF_LOG.LDF',  
SIZE = 3MB,  
MAXSIZE = 5MB,  
FILEGROWTH = 1MB)
USE AAF;
-- -----------------------------------------------------
-- Table `mydb`.`USUARIO`
-- -----------------------------------------------------
CREATE TABLE USUARIO (
  USUARIO_NO VARCHAR(45) NOT NULL,
  CI VARCHAR(20) NULL,
  NOMBRE VARCHAR(50) NULL,
  PATERNO VARCHAR(50) NULL,
  MATERNO VARCHAR(50) NULL,
  CARGO VARCHAR(100) NULL,
  PROFESION VARCHAR(100) NULL,
  USUARIO VARCHAR(45) NULL,
  PASSWORD VARBINARY(8000) NULL,
  PRIMARY KEY (USUARIO_NO))


-- -----------------------------------------------------
-- Table `mydb`.`PARTIDA`
-- -----------------------------------------------------
CREATE TABLE PARTIDA (
  PARTIDA_NO VARCHAR(45) NOT NULL,
  NOMBRE VARCHAR(150) NULL,
  PARTIDA INT NULL,
  VIDA_UTIL DECIMAL(10,2) NULL,
  COEFICIENTE DECIMAL(10,2) NULL,
  DEPRECIACION VARCHAR(45) NULL,
  ACTUALIZA VARCHAR(45) NULL,
  USUARIO_USUARIO_NO VARCHAR(45) NOT NULL,
  PRIMARY KEY (PARTIDA_NO),
  INDEX fk_PARTIDA_USUARIO1_idx (USUARIO_USUARIO_NO ASC),
  CONSTRAINT fk_PARTIDA_USUARIO1
    FOREIGN KEY (USUARIO_USUARIO_NO)
    REFERENCES USUARIO (USUARIO_NO))


-- -----------------------------------------------------
-- Table `mydb`.`OFICINA`
-- -----------------------------------------------------
CREATE TABLE OFICINA (
  OFICINA_NO VARCHAR(45) NOT NULL,
  DEPTO VARCHAR(45) NULL,
  COD_OFICINA VARCHAR(15) NULL,
  NOMBRE_OF VARCHAR(100) NULL,
  UBICACION VARCHAR(255) NULL,
  EMPLEADO_EMP_NO VARCHAR(45) NOT NULL,
  PRIMARY KEY (OFICINA_NO)
);
-- -----------------------------------------------------
-- Table `mydb`.`EMPLEADO`
-- -----------------------------------------------------
CREATE TABLE EMPLEADO (
  EMP_NO VARCHAR(45) NOT NULL,
  CI VARCHAR(20) NULL,
  EXP VARCHAR(10) NULL,
  NOMBRE VARCHAR(100) NULL,
  CARGO VARCHAR(100) NULL,
  UNIDAD VARCHAR(50) NULL,
  AREA_TRAB VARCHAR(55) NULL,
  CELULAR VARCHAR(10) NULL,
  PROFESION VARCHAR(100) NULL,
  USUARIO_USUARIO_NO VARCHAR(45) NOT NULL,
  OFICINA_OFICINA_NO VARCHAR(45) NOT NULL,
  PRIMARY KEY (EMP_NO),
  INDEX fk_EMPLEADO_USUARIO1_idx (USUARIO_USUARIO_NO ASC),
  INDEX fk_EMPLEADO_OFICINA1_idx (OFICINA_OFICINA_NO ASC),
  CONSTRAINT fk_EMPLEADO_USUARIO1
    FOREIGN KEY (USUARIO_USUARIO_NO)
    REFERENCES USUARIO (USUARIO_NO),
  CONSTRAINT fk_EMPLEADO_OFICINA1
    FOREIGN KEY (OFICINA_OFICINA_NO)
    REFERENCES OFICINA (OFICINA_NO))

ALTER TABLE OFICINA
DROP CONSTRAINT fk_OFICINA_EMPLEADO1 
-- -----------------------------------------------------
-- Table `mydb`.`INVENTARIO`
-- -----------------------------------------------------
CREATE TABLE INVENTARIO (
  INV_NO VARCHAR(45) NOT NULL,
  AUXILIAR VARCHAR(100) NULL,
  COD_ENTIDAD VARCHAR(50) NULL,
  COD_ANTIGUO VARCHAR(50) NULL,
  SERIE VARCHAR(100) NULL,
  DESCRIPCION VARCHAR(300) NULL,
  ESTADO VARCHAR(25) NULL,
  ESPECIFICA VARCHAR(50) NULL,
  PROCEDENCIA VARCHAR(45) NULL,
  FECHA_INGRESO DATETIME NULL,
  OBSERVACIONES VARCHAR(300) NULL,
  PARTIDA_PARTIDA_NO VARCHAR(45) NOT NULL,
  EMPLEADO_EMP_NO VARCHAR(45) NOT NULL,
  OFICINA_OFICINA_NO VARCHAR(45) NOT NULL,
  PRIMARY KEY (INV_NO),
  INDEX fk_INVENTARIO_PARTIDA1_idx (PARTIDA_PARTIDA_NO ASC),
  INDEX fk_INVENTARIO_EMPLEADO1_idx (EMPLEADO_EMP_NO ASC),
  INDEX fk_INVENTARIO_OFICINA1_idx (OFICINA_OFICINA_NO ASC),
  CONSTRAINT fk_INVENTARIO_PARTIDA1
    FOREIGN KEY (PARTIDA_PARTIDA_NO)
    REFERENCES PARTIDA (PARTIDA_NO),
  CONSTRAINT fk_INVENTARIO_EMPLEADO1
    FOREIGN KEY (EMPLEADO_EMP_NO)
    REFERENCES EMPLEADO (EMP_NO),
  CONSTRAINT fk_INVENTARIO_OFICINA1
    FOREIGN KEY (OFICINA_OFICINA_NO)
    REFERENCES OFICINA (OFICINA_NO))


